version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run:
          name: yarn install
          command: |
            yarn
      - run:
          name: firebase deploy
          command: |
            cp config/config.staging.js config.js && \
            yarn deploy --project "shinai-list-development" --token "$FIREBASE_TOKEN"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
